### ISSUE TITLE
Crashes randomly when crafting items while showing craftable recipes

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#159]
---- Minecraft Crash Report ----
// My bad.

Time: 2024-03-16 12:53:29
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.getFocusedRecipe(LegacyCraftingScreen.java:255)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.getFocusedResult(LegacyCraftingScreen.java:258)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.renderSelection(LegacyCraftingScreen.java:324)
	at wily.legacy.client.screen.LegacyCraftingScreen.method_25394(LegacyCraftingScreen.java:439)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$234(class_757.java)
	at net.minecraft.class_757.wrapOperation$zoj000$fabric-screen-api-v1$onRenderScreen(class_757.java:2111)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.getFocusedRecipe(LegacyCraftingScreen.java:255)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.getFocusedResult(LegacyCraftingScreen.java:258)
	at wily.legacy.client.screen.LegacyCraftingScreen$2.renderSelection(LegacyCraftingScreen.java:324)
	at wily.legacy.client.screen.LegacyCraftingScreen.method_25394(LegacyCraftingScreen.java:439)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$234(class_757.java)
	at net.minecraft.class_757.wrapOperation$zoj000$fabric-screen-api-v1$onRenderScreen(class_757.java:2111)

-- Screen render details --
Details:
	Screen name: wily.legacy.client.screen.LegacyCraftingScreen
	Mouse location: Scaled: (0, 0). Absolute: (-1.000000, -1.000000)
	Screen size: Scaled: (642, 361). Absolute: (1920, 1080). Scale factor of 2.993243
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Uptime --
Details:
	JVM uptime: 3335.532s
	Wall uptime: 3320.799s
	High-res time: 3318.437s
	Client ticks: 65838 ticks / 3291.900s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['WirCycle'/529382, l='ClientLevel', x=-519.44, y=64.00, z=558.60]]
	Chunk stats: 4096, 1261
	Level dimension: minecraft:overworld
	Level spawn location: World: (-464,64,128), Section: (at 0,0,0 in -29,4,8; chunk contains blocks -464,-64,128 to -449,319,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 8090 game time, 8090 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 178

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, friendsandfoes, iris, legacy, lithium, modmenu, nochatreports, nocreativedrift, simplefog, sodium, sspb, starlight

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1379257856 bytes (1315 MiB) / 3145728000 bytes (3000 MiB) up to 6308233216 bytes (6016 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32703.35
	Virtual memory used (MB): 13694.79
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 114.88
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6016m
	Fabric Mods: 
		architectury: Architectury 11.1.13
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.95.4+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.48+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.12+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.2+25e1b4764f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.73+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.31+eabbae364f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.62+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.52+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.33+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.55+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.1.0+0d29db764f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.9+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.5
			mixinextras: MixinExtras 0.3.2
		friendsandfoes: Friends&Foes 2.0.9
		iris: Iris 1.6.16
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		legacy: Legacy4J 1.5dev
		lithium: Lithium 0.12.1
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		nochatreports: No Chat Reports 1.20.4-v2.5.0
		nocreativedrift: NoCreativeDrift 1.20.1-5.0.0.0-fabric
		simplefog: Simple Fog Control 1.4.0
		sodium: Sodium 0.5.8+mc1.20.4
		sspb: Sodium Shadowy Path Blocks 3.2.1
		starlight: Starlight 1.1.3+fabric.f5dcd1a
	Loaded Shaderpack: (off)
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 18/18 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_CA
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['WirCycle'/529382, l='ServerLevel[New World]', x=-519.44, y=64.00, z=558.60]]
	Data Packs: vanilla, fabric, fabric-convention-tags-v1, friendsandfoes, legacy
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Wilyicaro** [comment]
Fixed in version 1.5.1, thanks for reporting.
If another crash issue with the Crafting Interface occurs, please refrain from commenting here as this specific crash has already been fully fixed.
