### ISSUE TITLE
Crashes with neoforge

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#211]
[latest.log](https://github.com/Wilyicaro/Legacy-Minecraft/files/15136215/latest.log)
Prism Launcher version: 8.3 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.35, 13.107.213.35]

textures.minecraft.net resolves to:
    [13.107.246.35, 13.107.213.35]

api.mojang.com resolves to:
    [13.107.246.35, 13.107.213.35]

Minecraft folder is:
C:/Users/Daniel/AppData/Roaming/PrismLauncher/instances/1.20.4/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Java is version 17.0.6, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/instances/1.20.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS
traits feature:is_quick_play_multiplayer

Libraries:
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-windows-arm64/3.3.2/lwjgl-freetype-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-windows-x86/3.3.2/lwjgl-freetype-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-windows/3.3.2/lwjgl-freetype-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.2/lwjgl-freetype-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.2/lwjgl-glfw-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2/lwjgl-glfw-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2/lwjgl-glfw-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.2/lwjgl-jemalloc-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2/lwjgl-jemalloc-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.2/lwjgl-jemalloc-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.2/lwjgl-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.2/lwjgl-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows/3.3.2/lwjgl-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.2/lwjgl-openal-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.2/lwjgl-openal-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.2/lwjgl-openal-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.2/lwjgl-opengl-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.2/lwjgl-opengl-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.2/lwjgl-opengl-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.2/lwjgl-stb-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.2/lwjgl-stb-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.2/lwjgl-stb-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.2/lwjgl-tinyfd-natives-windows-arm64-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.2/lwjgl-tinyfd-natives-windows-x86-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.2/lwjgl-tinyfd-natives-windows-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/prism-2024-02-29/ForgeWrapper-prism-2024-02-29.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/fancymodloader/earlydisplay/2.0.17/earlydisplay-2.0.17.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/fancymodloader/loader/2.0.17/loader-2.0.17.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/coremods/6.0.4/coremods-6.0.4.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/fancymodloader/spi/2.0.17/spi-2.0.17.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.24/securejarhandler-2.1.24.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/accesstransformers/at-modlauncher/10.0.1/at-modlauncher-10.0.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/accesstransformers/10.0.1/accesstransformers-10.0.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/mergetool/2.0.0/mergetool-2.0.0-api.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/bus/7.2.0/bus-7.2.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/JarJarSelector/0.4.0/JarJarSelector-0.4.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/JarJarMetadata/0.4.0/JarJarMetadata-0.4.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.1+mixin.0.8.5/sponge-mixin-0.13.1+mixin.0.8.5.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/jetbrains/annotations/22.0.0/annotations-22.0.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/srgutils/0.4.15/srgutils-0.4.15.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/machinezoo/noexception/noexception/1.7.1/noexception-1.7.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/neoforged/JarJarFileSystems/0.4.0/JarJarFileSystems-0.4.0.jar
  C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Mods:
  [✔] architectury-11.1.17-neoforge
  [✔] Legacy4J-1.20.4-1.6b-neoforge

Params:
  --username  --version 1.20.4 --gameDir C:/Users/Daniel/AppData/Roaming/PrismLauncher/instances/1.20.4/.minecraft --assetsDir C:/Users/Daniel/AppData/Roaming/PrismLauncher/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release --fml.neoForgeVersion 20.4.233 --fml.fmlVersion 2.0.17 --fml.mcVersion 1.20.4 --fml.neoFormVersion 20231207.154220 --launchTarget forgeclient

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6016m, -Duser.language=en]

Minecraft process ID: 6488

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
[21:17:27.994] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, WirCycle, --version, 1.20.4, --gameDir, C:/Users/Daniel/AppData/Roaming/PrismLauncher/instances/1.20.4/.minecraft, --assetsDir, C:/Users/Daniel/AppData/Roaming/PrismLauncher/assets, --assetIndex, 12, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --fml.neoForgeVersion, 20.4.233, --fml.fmlVersion, 2.0.17, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 20231207.154220, --launchTarget, forgeclient, --width, 854, --height, 480] 
[21:17:27.997] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.6 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0 
[21:17:28.094] [main/INFO] [loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow 
[21:17:28.186] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 
[21:17:28.331] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6 
[21:17:28.402] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Daniel/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.1+mixin.0.8.5/sponge-mixin-0.13.1+mixin.0.8.5.jar%23169!/ Service=ModLauncher Env=CLIENT 
[21:17:28.470] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 552.12, NVIDIA Corporation 
[21:17:28.504] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "architectury-11.1.17-neoforge.jar" of type MOD with provider {mods folder locator at C:\Users\Daniel\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft\mods} 
[21:17:28.504] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Legacy4J-1.20.4-1.6b-neoforge.jar" of type MOD with provider {mods folder locator at C:\Users\Daniel\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft\mods} 
[21:17:28.729] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "client-1.20.4-20231207.154220-srg.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@790132f7 
[21:17:28.729] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-20.4.233-universal.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@790132f7 
[21:17:28.817] [main/INFO] [loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection 
[21:17:28.817] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-neoforge-0.3.5.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@6579c3d9 
[21:17:29.554] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 
[21:17:29.562] [main/INFO] [LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.4, --gameDir, C:\Users\Daniel\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft, --assetsDir, C:\Users\Daniel\AppData\Roaming\PrismLauncher\assets, --uuid, <PROFILE ID>, --username, WirCycle, --assetIndex, 12, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480] 
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: wily/legacy/neoforge/LegacyMinecraftPlatformImpl
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: wily/legacy/neoforge/LegacyMinecraftPlatformImpl
	at TRANSFORMER/legacy@1.6b/wily.legacy.LegacyMinecraftPlatform.isLoadingMod(LegacyMinecraftPlatform.java)
	at TRANSFORMER/legacy@1.6b/wily.legacy.LegacyMixinPlugin.shouldApplyMixin(LegacyMixinPlugin.java:24)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:988)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:953)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
	at java.base/java.lang.Class.forName(Class.java:545)
	at MC-BOOTSTRAP/fml_earlydisplay@2.0.17/net.neoforged.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$19(DisplayWindow.java:593)
	at java.base/java.util.Optional.map(Optional.java:260)
	at MC-BOOTSTRAP/fml_earlydisplay@2.0.17/net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:593)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:85)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:206)
	at MC-BOOTSTRAP/fml_loader@2.0.17/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.ClassNotFoundException: wily.legacy.neoforge.LegacyMinecraftPlatformImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:193)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:193)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 47 more
Exiting with ERROR
Process exited with code 2.

**Comment by Wilyicaro** [comment]
Fixed in 1.6.1, thanks for reporting.
