### ISSUE TITLE
Turning off chat reports crashed my game.

### ISSUE THREAD

**Issue by Ucda1212** [Wilyicaro/Legacy-Minecraft#272]
Got this error log:
[19:57:01] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalArgumentException: duplicate event invoker for type interface fuzs.puzzleslib.api.event.v1.server.TagsUpdatedCallback
	at fuzs.puzzleslib.impl.event.core.EventInvokerImpl.register(EventInvokerImpl.java:74) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.event.FabricEventInvokerRegistryImpl.register(FabricEventInvokerRegistryImpl.java:430) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventInvokerRegistry.register(FabricEventInvokerRegistry.java:59) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.api.event.v1.core.FabricEventInvokerRegistry.register(FabricEventInvokerRegistry.java:45) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.event.FabricEventInvokerRegistryImpl.registerEventHandlers(FabricEventInvokerRegistryImpl.java:116) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.core.FabricFactories.registerEventHandlers(FabricFactories.java:65) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.impl.event.core.EventInvokerImpl.initialize(EventInvokerImpl.java:35) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at fuzs.puzzleslib.fabric.impl.client.event.FabricClientEventInvokers.lambda$registerLoadingHandlers$1(FabricClientEventInvokers.java:90) ~[PuzzlesLib-v20.4.42-1.20.4-Fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1+a67ffb5d4f-78d2a96fc756e69a.jar:?]
	at net.minecraft.class_310.handler$boc000$fabric-lifecycle-events-v1$onStart(class_310.java:11788) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:870) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:38) ~[notenoughcrashes-4.4.7+1.20.4-fabric.jar:?]
	at net.minecraft.class_310.modify$ean000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:24838) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[19:57:01] [Render thread/INFO]: Stopping!
[19:57:01] [Thread-11/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[19:57:01] [Thread-11/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[19:57:01] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[19:57:01] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[19:57:01] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
[19:57:01] [Render thread/INFO]: closing rrp ebe:base_resources
Process crashed with exitcode -1073740791.

**Comment by Wilyicaro** [comment]
Not a Legacy4J problem
