### ISSUE TITLE
Minecraft crashes with this mod

### ISSUE THREAD

**Issue by Bodolairicsko** [Wilyicaro/Legacy-Minecraft#425]
I wanted to play with this mod, but when launching the game crashes. I have updated my graphics drivers but still crashes out. I don't know what to do...

**Comment by Wilyicaro** [comment]
There is no way for me to guess which crash you are having, this is not usual, please send the crash report here.

**Comment by Bodolairicsko** [comment]
info: CONNECTING TO SERVER undefined
info: [2024-05-30T20:29:09Z INFO  rust_launcher::start::bindings] server: None
info: [2024-05-30T20:29:10Z INFO  rust_launcher::start] Loading version
info: {"versionSize":222025781,"state":{"VersionLoading":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":0}
info: [2024-05-30T20:29:10Z INFO  rust_launcher::start] Finished moving mods
info: [2024-05-30T20:29:10Z INFO  rust_launcher::start] Finished loading version
info: {"versionSize":222025781,"state":{"Downloading":["Libraries","Assets","Jre","Mods"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":77526}
info: [2024-05-30T20:29:10Z INFO  rust_launcher::start] Preparing assets
[2024-05-30T20:29:10Z INFO  rust_launcher::start] Preparing JRE
info: {"versionSize":222025781,"state":{"Downloading":["Libraries","Assets","Jre","Mods"]},"currentDownloadRate":80317,"eta":"about 1 hour","expectedTasks":6,"downloadSpeed":80317,"downloaded":77526}
info: [2024-05-30T20:29:11Z INFO  rust_launcher::start] Preparing libraries
info: {"versionSize":222025781,"state":{"Downloading":["Libraries","Assets","Mods"]},"currentDownloadRate":80317,"eta":"36 minutes","expectedTasks":6,"downloadSpeed":80317,"downloaded":48849815}
info: [2024-05-30T20:29:11Z INFO  rust_launcher::start] Preparing mods
info: [2024-05-30T20:29:11Z INFO  rust_launcher::start] Finished preparing mods
info: {"versionSize":222025781,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":80317,"eta":"about 1 hour","expectedTasks":6,"downloadSpeed":80317,"downloaded":647704512}
info: {"versionSize":222025781,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":3588885,"eta":"2 minutes","expectedTasks":6,"downloadSpeed":3588885,"downloaded":729685626}
info: {"versionSize":222025781,"state":{"Downloading":["Libraries"]},"currentDownloadRate":3588885,"eta":"3 minutes","expectedTasks":6,"downloadSpeed":3588885,"downloaded":845094151}
info: [2024-05-30T20:29:12Z INFO  rust_launcher::start] Finished preparing assets
info: {"versionSize":222025781,"state":{"Jvm":true},"currentDownloadRate":3588885,"eta":"3 minutes","expectedTasks":6,"downloadSpeed":3588885,"downloaded":943009870}
info: [2024-05-30T20:29:12Z INFO  rust_launcher::start] Finished preparing libraries
[2024-05-30T20:29:12Z INFO  rust_launcher::start] Preparing registry
[2024-05-30T20:29:12Z INFO  rust_launcher::start] Finished preparing registry
info: [2024-05-30T20:29:12Z INFO  rust_launcher::common::launch] starting JVM with arguments: ["-Djava.library.path=libraries/native\\net/digitalingot/fcef-windows/0.0.9\\extracted/;libraries/native\\net/digitalingot/fwebp-windows/0.0.2\\extracted/;libraries/native\\net/digitalingot/favif-windows/0.0.1\\extracted/;libraries/native\\com/discord/discord-game-sdk/3.2.1\\extracted/;libraries/native\\net/digitalingot/fdiscord/0.0.1\\extracted/;libraries/native\\net/digitalingot/fjni/0.0.1\\extracted/;libraries/native\\org/jitsi/jnopus/1.0\\extracted/;libraries/native\\org/lwjgl/lwjgl-freetype/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-jemalloc/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-openal/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-opengl/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-glfw/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-stb/3.3.3\\extracted/;libraries/native\\org/lwjgl/lwjgl-tinyfd/3.3.3\\extracted/", "--add-opens=java.desktop/java.awt.event=ALL-UNNAMED", "--add-opens=java.desktop/java.awt.color=ALL-UNNAMED", "--add-opens=java.desktop/java.awt=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-Xmx2048M", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:G1NewSizePercent=20", "-XX:G1ReservePercent=20", "-XX:MaxGCPauseMillis=50", "-XX:G1HeapRegionSize=32M", "-Dlog4j2.formatMsgNoLookups=true", "-XX:ErrorFile=feather/java_error.log", "-Djavax.accessibility.assistive_technologies=", "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT", "-Dfeather.overrideHardwareAccel=false", "-cp", "libraries\\java\\net/minecraft/client/1.20.6/minecraft-1.20.6.jar;libraries\\java\\net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar;libraries\\java\\org/ow2/asm/asm/9.6/asm-9.6.jar;libraries\\java\\org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar;libraries\\java\\org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar;libraries\\java\\org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar;libraries\\java\\org/ow2/asm/asm-util/9.6/asm-util-9.6.jar;libraries\\java\\net/fabricmc/intermediary/1.20.6/intermediary-1.20.6.jar;libraries/java\\net/fabricmc/fabric-loader/0.15.11/fabric-loader-0.15.11.jar;libraries\\java\\net/digitalingot/fjni/0.0.1/fjni-0.0.1.jar;libraries\\java\\net/digitalingot/fdiscord/0.0.1/fdiscord-0.0.1.jar;libraries\\java\\software/bernie/geckolib/geckolib-fabric-1.20.5-3.5.1.jar;libraries\\java\\net/digitalingot/rust-extension/1.0.7/rust-extension-1.0.7.jar;libraries\\java\\net/digitalingot/fcef/0.0.9/fcef-0.0.9.jar;libraries\\java\\net/digitalingot/fwebp/0.0.1/fwebp-0.0.1.jar;libraries\\java\\net/digitalingot/favif/0.0.1/favif-0.0.1.jar;libraries\\java\\net/digitalingot/feather-server-api/messaging/0.0.4/messaging-0.0.4-SNAPSHOT.jar;libraries\\java\\org/jitsi/libjitsi-opus/1.1-32-g2a5a8171/libjitsi-opus-1.1-32-g2a5a8171.jar;libraries\\java\\org/capnproto/runtime/0.1.10/runtime-0.1.10.jar;libraries\\java\\com/google/inject/guice/5.1.0/guice-vendored-5.1.0.jar;libraries\\java\\javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar;libraries\\java\\io/netty/netty-codec-http/4.1.97.Final/netty-codec-http-4.1.97.Final.jar;libraries\\java\\com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar;libraries\\java\\com/google/code/gson/gson/2.10.1/gson-2.10.1.jar;libraries\\java\\com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar;libraries\\java\\com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar;libraries\\java\\com/ibm/icu/icu4j/73.2/icu4j-73.2.jar;libraries\\java\\com/mojang/authlib/6.0.54/authlib-6.0.54.jar;libraries\\java\\com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar;libraries\\java\\com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar;libraries\\java\\com/mojang/datafixerupper/7.0.14/datafixerupper-7.0.14.jar;libraries\\java\\com/mojang/logging/1.2.7/logging-1.2.7.jar;libraries\\java\\com/mojang/patchy/2.2.10/patchy-2.2.10.jar;libraries\\java\\com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar;libraries\\java\\commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar;libraries\\java\\commons-io/commons-io/2.15.1/commons-io-2.15.1.jar;libraries\\java\\commons-logging/commons-logging/1.2/commons-logging-1.2.jar;libraries\\java\\io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar;libraries\\java\\io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar;libraries\\java\\io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar;libraries\\java\\io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar;libraries\\java\\io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar;libraries\\java\\it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar;libraries\\java\\net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar;libraries\\java\\net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar;libraries\\java\\net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;libraries\\java\\org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar;libraries\\java\\org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar;libraries\\java\\org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar;libraries\\java\\org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar;libraries\\java\\org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar;libraries\\java\\org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar;libraries\\java\\org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar;libraries\\java\\org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar;libraries\\java\\org/joml/joml/1.10.5/joml-1.10.5.jar;libraries\\java\\org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar;libraries\\java\\org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar;libraries\\java\\org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar;libraries\\java\\org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar", "-DFabricMcEmu= net.minecraft.client.main.Main ", "net.digitalingot.rustextension.ProxiedStart", "net.fabricmc.loader.launch.knot.KnotClient", "--username", "Ricsko0428", "--version", "1.20.6-feather", "--gameDir", "C:\\Users\\Otthoni\\AppData\\Roaming/.minecraft", "--assetsDir", "assets", "--assetIndex", "1.20.6-feather-game", "--uuid", "36932260fb6c484195296f39efe77fe2", "--accessToken", "<hidden>", "--userType", "msa", "--versionType", "feather"]
info: sending javaw pid
info: starting cleanup
info: [22:29:14] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
info: [22:29:14] [ForkJoinPool-1-worker-4/WARN]: Mod feather uses the version release/31b3014e which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'release/31b3014e'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
info: [22:29:15] [main/INFO]: Loading 57 mods:
	- architectury 12.1.2
	- fabric-api 0.99.0+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51b0
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bb0
	   |-- fabric-biome-api-v1 13.0.25+be5d88beb0
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bb0
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51b0
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51b0
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bb0
	   |-- fabric-command-api-v1 1.2.45+f71b366fb0
	   |-- fabric-command-api-v2 2.2.24+80f8cf51b0
	   |-- fabric-commands-v0 0.2.62+df3654b3b0
	   |-- fabric-content-registries-v0 8.0.5+b82b2392b0
	   |-- fabric-convention-tags-v1 2.0.4+7f945d5bb0
	   |-- fabric-convention-tags-v2 2.1.0+70fd1b46b0
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51b0
	   |-- fabric-data-attachment-api-v1 1.1.16+2a2c66b6b0
	   |-- fabric-data-generation-api-v1 19.2.0+a5d5299db0
	   |-- fabric-dimensions-v1 2.1.68+94793913b0
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bb0
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3b0
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51b0
	   |-- fabric-item-api-v1 8.2.1+8e8943b6b0
	   |-- fabric-item-group-api-v1 4.0.39+aae0949ab0
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51b0
	   |-- fabric-keybindings-v0 0.2.43+df3654b3b0
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3b0
	   |-- fabric-loot-api-v2 3.0.5+97f703dab0
	   |-- fabric-message-api-v1 6.0.11+a7dc0e41b0
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51b0
	   |-- fabric-models-v0 0.4.11+9386d8a7b0
	   |-- fabric-networking-api-v1 4.0.8+0dca0349b0
	   |-- fabric-object-builder-api-v1 15.1.4+c5fc38b3b0
	   |-- fabric-particles-v1 4.0.0+c5fc38b3b0
	   |-- fabric-recipe-api-v1 5.0.3+c5fc38b3b0
	   |-- fabric-registry-sync-v0 5.0.16+ad474493b0
	   |-- fabric-renderer-api-v1 3.2.12+97f703dab0
	   |-- fabric-renderer-indigo 1.5.12+80f8cf51b0
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3b0
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb0
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb0
	   |-- fabric-rendering-v0 1.1.64+df3654b3b0
	   |-- fabric-rendering-v1 4.2.4+b21c00cbb0
	   |-- fabric-resource-conditions-api-v1 4.2.0+a5d5299db0
	   |-- fabric-resource-loader-v0 1.1.0+c0e5481fb0
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8ab0
	   |-- fabric-screen-handler-api-v1 1.3.73+8c7b71c2b0
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3b0
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3b0
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560b0
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- feather release/31b3014e
	- java 21
	- legacy 1.6.7
	   \-- io_github_libsdl4j_libsdl4j 2.28.4-1.6
	- minecraft 1.20.6
info: [22:29:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Otthoni/AppData/Roaming/.minecraft/libraries/java/net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
info: [22:29:15] [main/INFO]: Compatibility level set to JAVA_16
info: [22:29:15] [main/INFO]: Compatibility level set to JAVA_17
info: [22:29:16] [main/INFO]: Compatibility level set to JAVA_21
info: [22:29:16] [main/INFO]: Feather: Optifine dectected? false
info: [22:29:16] [main/INFO]: [Feather::EssentialMod] Installed: false
info: [22:29:17] [main/WARN]: Error loading class: com/terraformersmc/modmenu/config/option/EnumConfigOption (java.lang.ClassNotFoundException: com/terraformersmc/modmenu/config/option/EnumConfigOption)
info: [22:29:17] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
info: [22:29:31] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
info: [22:29:31] [Render thread/WARN]: @Redirect conflict. Skipping legacy-common.mixins.json:MinecraftMixin from mod legacy->@Redirect::setLevelLoadingScreen(Lnet/minecraft/class_310;Lnet/minecraft/class_437;Lnet/minecraft/class_638;)V with priority 1000, already redirected by mixins.feather.json:yxnlZ from mod feather->@Redirect::iNyLh(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000
info: [22:29:32] [Render thread/WARN]: @Redirect conflict. Skipping legacy-common.mixins.json:MinecraftMixin from mod legacy->@Redirect::setLevelLoadingScreen(Lnet/minecraft/class_310;Lnet/minecraft/class_437;Lnet/minecraft/class_638;)V with priority 1000, already redirected by mixins.feather.json:yxnlZ from mod feather->@Redirect::iNyLh(Lnet/minecraft/class_310;Lnet/minecraft/class_437;)V with priority 1000
info: [22:29:32] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.15.11.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) [rust-extension-1.0.7.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:233) ~[minecraft-1.20.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:233) ~[minecraft-1.20.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector setLevelLoadingScreen(Lnet/minecraft/class_310;Lnet/minecraft/class_437;Lnet/minecraft/class_638;)V in legacy-common.mixins.json:MinecraftMixin from mod legacy failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Legacy4J-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:233) ~[minecraft-1.20.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 5 more
info: [2024-05-30T20:29:32Z INFO  rust_launcher::start::bindings] launch stalled

**Comment by Bodolairicsko** [comment]
idk its bc that i launch it from feather, but in original it doesnt load the mod in

**Comment by Wilyicaro** [comment]
The Feather launcher is causing this, it makes some modification to Mixin, which conflicts with Legacy4J
