### ISSUE TITLE
Missing SDL_GameControllerGetFirmwareVersion from the mod that ultimately ending in a crash during launch (i use the v.1.20.4 of the mod)

### ISSUE THREAD

**Issue by Mollusksux** [Wilyicaro/Legacy-Minecraft#476]
This is what essentially came out of the logs containing the crash (im sorry if i misdiagnose the problem, the game crashes when the main title showed up and i cant even play like at all) :

```
13:50:38.524
Found unifont_all_no_pua-15.1.04.hex, loading
13:50:40.149
Unhandled game exception
java.lang.UnsatisfiedLinkError: Error looking up function 'SDL_GameControllerGetFirmwareVersion': The specified procedure could not be found.

	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:620)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:596)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:582)
	at com.sun.jna.Native.register(Native.java:1904)
	at io.github.libsdl4j.jna.SdlNativeLibraryLoader.registerNativeMethods(SdlNativeLibraryLoader.java:26)
	at io.github.libsdl4j.api.gamecontroller.SdlGamecontroller.<clinit>(SdlGamecontroller.java:69)
	at wily.legacy.client.controller.SDLControllerHandler.applyGamePadMappingsFromBuffer(SDLControllerHandler.java:136)
	at wily.legacy.client.controller.Controller$Handler.tryDownloadAndApplyNewMappings(Controller.java:62)
	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:33)
	at wily.legacy.client.controller.ControllerManager.setup(ControllerManager.java:55)
	at wily.legacy.Legacy4JClient.lambda$init$14(Legacy4JClient.java:251)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$0(EventHandlerImpl.java:50)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35)
	at net.minecraft.class_310.handler$zip000$fabric-lifecycle-events-v1$onStart(class_310.java:4788)
	at net.minecraft.class_310.method_1514(class_310.java:870)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
13:50:40.534
Stopping!
13:50:41.395
Shutdown failure!
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.forEach(HashMap.java:1424)
	at net.minecraft.class_1060.close(class_1060.java:173)
	at net.minecraft.class_310.close(class_310.java:1246)
	at net.minecraft.class_310.method_1490(class_310.java:1220)
	at net.minecraft.client.main.Main.main(Main.java:281)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
13:50:41.690

13:50:41.690
Process ended with exit code 0
```

**Comment by Wilyicaro** [comment]
Fixed in version 1.7, thanks for reporting.
